import { useState } from 'react'
import { useResource } from './api'
import { useApp } from './context'
import { ErrorNotice, Loading, PageHeader } from './components'
import { Pager } from './pagination'
import type { Page, Ranking } from './types'

type Insights = {books_finished: number; completed_attempts: number; rereads_finished: number; currently_reading: number; undated_completions: number; rated_books: number; unrated_books: number; months: {month: string; count: number}[]; rating_distribution: {rating: number; count: number}[]; favourite_authors: {id: number; name: string; books_finished: number; rated_books: number; average_rating: number | null}[]}
type Membership = {id: number; title: string; kind: string}
export type CollectionContext = Record<string, {rating: number | null; status: string | null; read: boolean; lists: Membership[]}>
type OverlapWork = {id: number; title: string; authors: string[]; genres: string[]; read: boolean; lists: Membership[]; list_count: number}

export function LibraryNavigation({view, setView}: {view: string; setView: (view: string) => void}) {
  const facets = useResource<{genres: string[]}>('/api/works/facets/')
  const genre = new URLSearchParams(window.location.hash.split('?')[1] || '').get('genre') || ''
  return <><nav className="tabs" aria-label="Library views">{[['books','My books'],['next','Read next'],['goals','Goals & years'],['insights','Reading insights'],['overlap','Collection overlap']].map(([key,text]) => <button className={`tab ${view === key ? 'active' : ''}`} aria-pressed={view === key} key={key} onClick={() => setView(key)}>{text}</button>)}</nav>{['books', 'next', 'overlap'].includes(view) && <div className="toolbar"><select className="filter-select" aria-label={`Filter ${view === 'books' ? 'library' : view === 'next' ? 'read-next list' : 'collection overlap'} by genre`} value={genre} onChange={event => { const params = new URLSearchParams(); if (view !== 'books') params.set('view', view); if (event.target.value) params.set('genre', event.target.value); window.location.hash = `/library${params.size ? `?${params}` : ''}` }}><option value="">All genres</option>{facets.data?.genres.map(value => <option value={value} key={value}>{value}</option>)}</select></div>}</>
}

export function ReadingInsights() {
  const {version} = useApp()
  const result = useResource<Insights>('/api/reading-insights/', version)
  if (result.error) return <ErrorNotice>{result.error}</ErrorNotice>
  if (!result.data) return <Loading />
  const d = result.data, maxMonth = Math.max(1, ...d.months.map(m => m.count)), maxRating = Math.max(1,...d.rating_distribution.map(r => r.count))
  return <><PageHeader eyebrow="Your reading life" title="Reading insights.">Based on your saved reading history and personal ratings.</PageHeader><div className="insight-stats">{[[d.books_finished,'Unique books finished'],[d.completed_attempts,'Completed readings'],[d.rereads_finished,'Rereads completed'],[d.currently_reading,'Currently reading']].map(([value,text]) => <div className="panel panel-body" key={text}><strong>{value}</strong><span>{text}</span></div>)}</div><div className="two-column"><section className="panel"><div className="panel-header"><h2>Reading over the last year</h2></div><div className="panel-body"><p className="small-text muted">Completed readings by finish date, including rereads. {d.undated_completions} completions have no finish date and are excluded from this chart.</p><div className="insight-bars">{d.months.map(m => <div className="insight-bar-row" key={m.month}><span>{new Date(`${m.month}-01T12:00:00`).toLocaleDateString('en-GB',{month:'short',year:'2-digit'})}</span><div className="insight-track"><span style={{width:`${m.count/maxMonth*100}%`}} /></div><strong>{m.count}</strong></div>)}</div></div></section><section className="panel"><div className="panel-header"><h2>Your rating distribution</h2></div><div className="panel-body"><p className="small-text muted">Current library ratings: {d.rated_books} rated · {d.unrated_books} unrated. Earlier attempt ratings stay in reading history.</p><div className="insight-bars">{d.rating_distribution.map(r => <div className="insight-bar-row" key={r.rating}><span>★ {r.rating}/10</span><div className="insight-track gold"><span style={{width:`${r.count/maxRating*100}%`}} /></div><strong>{r.count}</strong></div>)}</div></div></section></div><section className="panel"><div className="panel-header"><h2>Your favourite authors</h2></div><div className="panel-body"><p className="small-text muted">Ordered by average personal rating, then number of rated books and unique books finished. Small samples are shown explicitly.</p>{d.favourite_authors.map(a => <div className="source-card" key={a.id}><a className="book-title" href={`#/authors/${a.id}`}>{a.name}</a><p>{a.average_rating == null ? 'No current rating' : `★ ${a.average_rating}/10 average`} · {a.rated_books} rated books · {a.books_finished} books finished</p></div>)}{!d.favourite_authors.length && <p>Rate a book or mark one finished to start seeing authors here.</p>}</div></section></>
}

export function MembershipLinks({lists}: {lists: Membership[]}) {
  return <ul className="membership-links">{lists.map(l => <li key={l.id}><a href={`#/rankings/${l.id}`}>{l.title}</a><small className="muted"> · {l.kind}</small></li>)}</ul>
}

export function CollectionOverlap() {
  const {version} = useApp()
  const [search,setSearch] = useState(''), [read,setRead] = useState(''), [ranking,setRanking] = useState(''), [genre] = useState(() => new URLSearchParams(window.location.hash.split('?')[1] || '').get('genre') || ''), [page,setPage] = useState(1)
  const ranks = useResource<Ranking[]>('/api/rankings/', version, true)
  const result = useResource<Page<OverlapWork>>(`/api/collection-overlap/?${new URLSearchParams({search, read, ranking, genre, page:String(page)})}`, version)
  return <><PageHeader eyebrow="Connections across your reading" title="Collection overlap.">Find books appearing in two or more shared rankings or reading collections. List counts show overlap, not a new quality ranking. “Already read” includes completed earlier attempts.</PageHeader><div className="toolbar"><input className="search-input" aria-label="Search overlapping books" placeholder="Search title or author…" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} /><select className="filter-select" aria-label="Overlap reading status" value={read} onChange={e=>{setRead(e.target.value);setPage(1)}}><option value="">All books</option><option value="yes">Already read</option><option value="no">Not recorded as read</option></select><select className="filter-select" aria-label="Choose ranking or collection" value={ranking} onChange={e=>{setRanking(e.target.value);setPage(1)}}><option value="">All shared lists</option>{ranks.data?.filter(r=>r.origin!=='personal' && r.item_type==='work').map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></div>{result.error && <ErrorNotice>{result.error}</ErrorNotice>}{result.loading ? <Loading /> : <section className="panel panel-body">{result.data?.results.map(w=><article className="source-card" key={w.id}><a className="book-title" href={`#/books/${w.id}`}>{w.title}</a><p className="book-author">{w.authors.join(', ')}</p><div className="book-meta"><span className="pill gold">{w.list_count} shared lists</span><span className={`pill ${w.read ? 'green' : 'muted'}`}>{w.read ? '✓ Already read' : 'Not recorded as read'}</span></div><details><summary>See rankings & collections</summary><MembershipLinks lists={w.lists}/></details></article>)}{!result.data?.results.length && <p>No overlapping books match these filters.</p>}</section>}<Pager page={page} data={result.data} setPage={setPage} loading={result.loading}/></>
}
