"""Generate TypeScript and runtime response contracts without reading private rows."""
import json
from pathlib import Path
from django.conf import settings
from django.core.management.base import BaseCommand, CommandError
from rest_framework import serializers as s
from backend.core.api_contracts import computed_fields, contract_registry


def schema_field(field, serializer=None, name=None):
    if isinstance(field, s.ListSerializer):
        value = {'kind': 'array', 'item': schema_object(field.child)}
    elif isinstance(field, s.BaseSerializer):
        value = schema_object(field)
    elif isinstance(field, s.ChoiceField):
        value = {'kind': 'enum', 'values': list(field.choices)}
    elif isinstance(field, s.BooleanField):
        value = {'kind': 'boolean'}
    elif isinstance(field, (s.IntegerField, s.FloatField, s.PrimaryKeyRelatedField)):
        value = {'kind': 'number'}
    elif isinstance(field, s.DecimalField):
        value = {'kind': 'string' if getattr(field, 'coerce_to_string', True) else 'number'}
    elif isinstance(field, s.ListField):
        value = {'kind': 'array', 'item': schema_field(field.child)}
    elif isinstance(field, s.DictField):
        value = {'kind': 'record', 'item': schema_field(field.child)}
    elif isinstance(field, (s.CharField, s.DateField, s.DateTimeField, s.ImageField, s.FileField)):
        value = {'kind': 'string'}
    else:
        value = {'kind': 'unknown'}
    nullable = field.allow_null or isinstance(field, (s.FileField, s.ImageField))
    model = getattr(getattr(serializer, 'Meta', None), 'model', None)
    if model and isinstance(field, s.BaseSerializer):
        try:
            nullable = nullable or model._meta.get_field((field.source or name).split('.')[0]).null
        except Exception:
            pass
    if nullable:
        value['nullable'] = True
    return value


def schema_object(serializer):
    overrides = computed_fields(serializer)
    model = getattr(getattr(serializer, 'Meta', None), 'model', None)
    fields = {name: schema_field(overrides.get(name, field), serializer, name)
              for name, field in serializer.fields.items() if not field.write_only}
    required = [name for name, field in serializer.fields.items() if not field.write_only
                and (model is not None or field.required or field.read_only or field.default is not s.empty)]
    return {'kind': 'object', 'fields': fields, 'required': required}


def type_for(schema):
    kind = schema['kind']
    if kind == 'object':
        value = '{\n' + '\n'.join('  '+json.dumps(name)+('' if name in schema['required'] else '?')+': '+type_for(field)+';'
                                  for name, field in schema['fields'].items())+'\n}'
    elif kind == 'array': value = f"Array<{type_for(schema['item'])}>"
    elif kind == 'record': value = f"Record<string, {type_for(schema['item'])}>"
    elif kind == 'enum': value = ' | '.join(json.dumps(item, ensure_ascii=False) for item in schema['values']) or 'string'
    else: value = kind
    return value + (' | null' if schema.get('nullable') and kind != 'unknown' else '')


def contracts():
    registry = {name: schema_object(cls()) for name, cls in contract_registry().items()}
    header = '// Generated by manage.py export_frontend_contracts. Do not edit.\n'
    types = header + '// Open JSON fields remain unknown; computed response fields use explicit contracts.\n\n'
    types += '\n'.join(f'export type {name} = {type_for(schema)}\n' for name, schema in registry.items())
    # Only complex action envelopes are needed by the runtime boundary guard.
    guarded = ['ApiCatalogFacets', 'ApiAppSearchResponse', 'ApiBibliographyExport', 'ApiBulkBookActionResult', 'ApiCatalogAtlas', 'ApiPublishedComparison', 'ApiCalendarState', 'ApiCalendarPreview', 'ApiStudyDelta', 'ApiStudyRecordsPage', 'ApiStudyHistoryPage', 'ApiPlanSuggestion', 'ApiAllocationPreview', 'ApiRankingBrowsePage',
               'ApiRecommendationBundle', 'ApiRecommendationPreferences', 'ApiRecommendationFeedbackPage', 'ApiRecommendationFeedback']
    runtime = header + 'export const responseSchemas = ' + json.dumps({name: registry[name] for name in guarded}, ensure_ascii=False, separators=(',', ':')) + ' as const\n'
    return {'apiContracts.ts': types, 'responseSchemas.ts': runtime}


class Command(BaseCommand):
    help = 'Generate TypeScript and runtime response schemas; --check detects drift without database reads.'
    def add_arguments(self, parser): parser.add_argument('--check', action='store_true')
    def handle(self, *args, **options):
        for name, rendered in contracts().items():
            output = Path(settings.BASE_DIR) / 'frontend/src/generated' / name
            if options['check']:
                if not output.is_file() or output.read_text() != rendered:
                    raise CommandError('API contracts changed. Run manage.py export_frontend_contracts and rebuild.')
            else:
                output.parent.mkdir(parents=True, exist_ok=True)
                output.write_text(rendered)
        self.stdout.write('Frontend API contracts match the serializers.' if options['check'] else 'Frontend API contracts generated.')
