# Generated by Django 5.2.17 on 2026-09-12 00:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Edition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("language", models.CharField(default="English", max_length=60)),
                ("translator", models.CharField(blank=True, max_length=240)),
                ("publisher", models.CharField(blank=True, max_length=240)),
                ("isbn", models.CharField(blank=True, max_length=30)),
                (
                    "pages",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "word_count",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("abridged", models.BooleanField(default=False)),
                ("translation_notes", models.TextField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                ("cover", models.ImageField(blank=True, upload_to="covers/%Y/%m/")),
                ("image_attribution", models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=240)),
                ("biography", models.TextField(blank=True)),
                ("countries", models.JSONField(blank=True, default=list)),
                (
                    "portrait",
                    models.ImageField(blank=True, upload_to="portraits/%Y/%m/"),
                ),
                ("image_attribution", models.CharField(blank=True, max_length=500)),
                ("source_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("kind", models.CharField(default="topic", max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=100)),
                (
                    "pages_per_day",
                    models.PositiveIntegerField(
                        default=25,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2000),
                        ],
                    ),
                ),
                (
                    "words_per_minute",
                    models.PositiveIntegerField(
                        default=250,
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(2000),
                        ],
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("system", "system"),
                            ("light", "light"),
                            ("dark", "dark"),
                        ],
                        default="system",
                        max_length=10,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Ranking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("title", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                ("domain", models.CharField(default="literature", max_length=30)),
                (
                    "item_type",
                    models.CharField(
                        choices=[("work", "Work"), ("person", "Person")],
                        default="work",
                        max_length=10,
                    ),
                ),
                (
                    "presentation",
                    models.CharField(
                        choices=[
                            ("ranked", "ranked"),
                            ("unranked", "unranked"),
                            ("reading_sequence", "reading_sequence"),
                        ],
                        default="ranked",
                        max_length=20,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("curated", "curated"),
                            ("external", "external"),
                            ("personal", "personal"),
                        ],
                        default="curated",
                        max_length=20,
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("share_token", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("sharing_enabled", models.BooleanField(default=False)),
                ("scope", models.JSONField(blank=True, default=dict)),
                ("target_size", models.PositiveIntegerField(default=100)),
                (
                    "status",
                    models.CharField(default="awaiting_research", max_length=50),
                ),
                ("source_url", models.URLField(blank=True)),
                ("publisher", models.CharField(blank=True, max_length=200)),
                ("last_researched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_sources_checked_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("criteria", models.JSONField(blank=True, default=list)),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["title", "id"],
            },
        ),
        migrations.CreateModel(
            name="RankingPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bookmarked", models.BooleanField(default=False)),
                (
                    "refresh_interval_days",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3650),
                        ],
                    ),
                ),
                ("refresh_requested_at", models.DateTimeField(blank=True, null=True)),
                ("weights", models.JSONField(blank=True, default=dict)),
                ("overrides", models.JSONField(blank=True, default=dict)),
                (
                    "ranking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="core.ranking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RankingRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(max_length=300)),
                ("snapshot", models.JSONField(default=dict)),
                (
                    "ranking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="core.ranking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_id", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(max_length=1000)),
                ("family", models.CharField(max_length=80)),
                ("publisher", models.CharField(blank=True, max_length=240)),
                ("evidence", models.TextField(blank=True)),
                ("limitations", models.TextField(blank=True)),
                ("consulted_on", models.DateField(blank=True, null=True)),
                ("eligible", models.BooleanField(default=False)),
                ("underlying_source_id", models.CharField(max_length=200)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "ranking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="core.ranking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                (
                    "form",
                    models.CharField(
                        choices=[
                            ("book", "book"),
                            ("essay", "essay"),
                            ("short_story", "short_story"),
                            ("poem", "poem"),
                            ("play", "play"),
                            ("collection", "collection"),
                        ],
                        default="book",
                        max_length=20,
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("literature", "literature"),
                            ("philosophy", "philosophy"),
                            ("nonfiction", "nonfiction"),
                        ],
                        default="literature",
                        max_length=30,
                    ),
                ),
                ("original_year", models.IntegerField(blank=True, null=True)),
                ("original_language", models.CharField(blank=True, max_length=60)),
                ("countries", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True)),
                (
                    "reading_load",
                    models.CharField(
                        choices=[
                            ("leisure", "leisure"),
                            ("classic_literature", "classic_literature"),
                            ("demanding_literature", "demanding_literature"),
                            ("philosophy", "philosophy"),
                        ],
                        default="classic_literature",
                        max_length=30,
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True, related_name="works", to="core.person"
                    ),
                ),
                (
                    "contained_in",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contents",
                        to="core.work",
                    ),
                ),
                (
                    "default_edition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.edition",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="core.tag")),
            ],
            options={
                "ordering": ["title", "id"],
            },
        ),
        migrations.CreateModel(
            name="RankingEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=1)),
                (
                    "source_rank",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("assessments", models.JSONField(blank=True, default=dict)),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.person",
                    ),
                ),
                (
                    "ranking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="core.ranking",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.work",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="PlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("month", models.DateField(help_text="First day of the month")),
                ("position", models.PositiveIntegerField(default=1)),
                ("pages", models.PositiveIntegerField(blank=True, null=True)),
                ("locked", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.work"
                    ),
                ),
            ],
            options={
                "ordering": ["month", "position", "id"],
            },
        ),
        migrations.CreateModel(
            name="LibraryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("want_to_read", "want_to_read"),
                            ("reading", "reading"),
                            ("paused", "paused"),
                            ("finished", "finished"),
                            ("abandoned", "abandoned"),
                        ],
                        default="want_to_read",
                        max_length=20,
                    ),
                ),
                ("current_page", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "edition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.edition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.work"
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="edition",
            name="work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="editions",
                to="core.work",
            ),
        ),
        migrations.AddConstraint(
            model_name="ranking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_public", False),
                        ("origin", "personal"),
                        ("owner__isnull", False),
                    ),
                    models.Q(
                        models.Q(("origin", "personal"), _negated=True),
                        ("owner__isnull", True),
                        ("sharing_enabled", False),
                    ),
                    _connector="OR",
                ),
                name="ranking_ownership_and_visibility",
            ),
        ),
        migrations.AddConstraint(
            model_name="rankingpreference",
            constraint=models.UniqueConstraint(
                fields=("user", "ranking"), name="unique_ranking_preference"
            ),
        ),
        migrations.AddConstraint(
            model_name="rankingrevision",
            constraint=models.UniqueConstraint(
                fields=("ranking", "number"), name="unique_ranking_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="researchsource",
            constraint=models.UniqueConstraint(
                fields=("ranking", "underlying_source_id"), name="unique_target_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="researchsource",
            constraint=models.UniqueConstraint(
                fields=("ranking", "source_id"), name="unique_target_source_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="researchsource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("eligible", False),
                    models.Q(
                        ("consulted_on__isnull", False),
                        models.Q(("evidence", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="eligible_source_has_consulted_evidence",
            ),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(
                fields=["field", "form"], name="core_work_field_b34484_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(
                fields=["original_year"], name="core_work_origina_94ef02_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rankingentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("person__isnull", True), ("work__isnull", False)),
                    models.Q(("person__isnull", False), ("work__isnull", True)),
                    _connector="OR",
                ),
                name="entry_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="rankingentry",
            constraint=models.UniqueConstraint(
                fields=("ranking", "work"), name="unique_ranking_work"
            ),
        ),
        migrations.AddConstraint(
            model_name="rankingentry",
            constraint=models.UniqueConstraint(
                fields=("ranking", "person"), name="unique_ranking_person"
            ),
        ),
        migrations.AddConstraint(
            model_name="rankingentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)), name="entry_position_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="rankingentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_rank__isnull", True),
                    ("source_rank__gte", 1),
                    _connector="OR",
                ),
                name="entry_rank_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="planitem",
            constraint=models.UniqueConstraint(
                fields=("user", "work", "month"), name="unique_plan_work_month"
            ),
        ),
        migrations.AddConstraint(
            model_name="planitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("month__day", 1)), name="plan_month_first_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="planitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)), name="plan_position_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="planitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pages__isnull", True), ("pages__gte", 1), _connector="OR"
                ),
                name="plan_pages_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="libraryitem",
            constraint=models.UniqueConstraint(
                fields=("user", "work"), name="unique_library_work"
            ),
        ),
        migrations.AddConstraint(
            model_name="edition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pages__isnull", True), ("pages__gte", 1), _connector="OR"
                ),
                name="edition_pages_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="edition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("word_count__isnull", True),
                    ("word_count__gte", 1),
                    _connector="OR",
                ),
                name="edition_words_positive",
            ),
        ),
    ]
