# Generated by Django 5.2.17 on 2026-09-12 00:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ranking",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rankingentry",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="researchsource",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tag",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="difficulty_aware_planning",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="pages_per_month",
            field=models.PositiveIntegerField(
                default=750,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(62000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pages_per_week",
            field=models.PositiveIntegerField(
                default=175,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(14000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="reading_days_per_week",
            field=models.PositiveIntegerField(
                default=4,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(7),
                ],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="reading_target_period",
            field=models.CharField(
                choices=[("day", "Reading day"), ("week", "Week"), ("month", "Month")],
                default="week",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="work",
            name="reading_effort_override",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.25),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
