# Generated by Django 5.2.17 on 2026-09-13 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_shared_deletion_guards"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryitem",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="libraryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rating__isnull", True),
                    models.Q(("rating__gte", 1), ("rating__lte", 10)),
                    _connector="OR",
                ),
                name="library_rating_1_to_10",
            ),
        ),
    ]
