# Generated by Django 5.2.17 on 2026-09-13 19:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_libraryitem_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryitem",
            name="finished_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="libraryitem",
            name="started_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ReadingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(max_length=20)),
                ("current_page", models.PositiveIntegerField(default=0)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("started_on", models.DateField(blank=True, null=True)),
                ("finished_on", models.DateField(blank=True, null=True)),
                (
                    "edition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.edition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.work"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("rating__isnull", True),
                            models.Q(("rating__gte", 1), ("rating__lte", 10)),
                            _connector="OR",
                        ),
                        name="attempt_rating_range",
                    )
                ],
            },
        ),
    ]
