# Generated by Django 5.2.17 on 2026-09-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_libraryitem_finished_on_libraryitem_started_on_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthRateLimit",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
        ),
    ]
