# Generated by Django 5.2.17 on 2026-09-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_authratelimit"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="registration_pending",
            field=models.BooleanField(default=False),
        ),
    ]
