# Generated by Django 5.2.17 on 2026-09-13 19:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_user_registration_pending"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryitem",
            name="personal_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="libraryitem",
            name="read_next_position",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="libraryitem",
            name="shelves",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="work",
            name="field",
            field=models.CharField(
                choices=[
                    ("literature", "literature"),
                    ("philosophy", "philosophy"),
                    ("nonfiction", "nonfiction"),
                    ("manga", "manga"),
                ],
                default="literature",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ReadingGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2200),
                        ]
                    ),
                ),
                (
                    "books",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "pages",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "year"), name="unique_reading_goal_year"
                    )
                ],
            },
        ),
    ]
