# Generated by Django 5.2.17 on 2026-09-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_libraryitem_personal_tags_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="rankingentry",
            index=models.Index(
                fields=["work", "is_archived", "position"],
                name="rank_entry_work_live_pos",
            ),
        ),
    ]
