# Generated by Django 5.2.17 on 2026-09-27 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_guards(apps, schema_editor):
    # SQLite may rebuild Edition when adding non-null columns. A schema rebuild
    # drops custom triggers; reinstall every guard, also after a reverse migrate.
    if schema_editor.connection.vendor == 'sqlite':
        from importlib import import_module
        guards = import_module('backend.core.migrations.0003_shared_deletion_guards').GUARDS
        for table, condition in guards.items():
            when = f' WHEN {condition}' if condition else ''
            schema_editor.execute(f"CREATE TRIGGER IF NOT EXISTS protect_{table}_deletion BEFORE DELETE ON {table}{when} "
                                  "BEGIN SELECT RAISE(ABORT, 'Shared records must be archived, not deleted'); END")
    elif schema_editor.connection.vendor != 'postgresql':
        raise RuntimeError('Deletion guards require SQLite or PostgreSQL.')


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_classical_study_profile"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, preserve_guards),
        migrations.AddField(
            model_name="edition",
            name="cover_basis",
            field=models.CharField(
                choices=[
                    ("unknown", "Basis not recorded"),
                    ("representative_work", "Representative work image"),
                    ("edition_matched", "Edition-matched image"),
                    ("manually_supplied", "Manually supplied"),
                ],
                default="unknown",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="edition",
            name="cover_source_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="edition",
            name="pages_basis",
            field=models.CharField(
                choices=[
                    ("unknown", "Basis not recorded"),
                    ("isbn_matched", "ISBN-matched provider record"),
                    ("estimated_across_editions", "Estimate across editions"),
                    ("manually_recorded", "Manually recorded"),
                ],
                default="unknown",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="edition",
            name="pages_source_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="libraryitem",
            name="reading_basis",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="planitem",
            name="reading_basis",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="readingattempt",
            name="reading_basis",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="ReadingAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("method", models.CharField(max_length=30)),
                ("before", models.JSONField(default=dict)),
                ("after", models.JSONField(default=dict)),
                (
                    "library_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.libraryitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.work"
                    ),
                ),
            ],
        ),
        migrations.RunPython(preserve_guards, migrations.RunPython.noop),
    ]
