# Generated by Django 5.2.17 on 2026-09-28 22:48

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_freeze_existing_reading_basis"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogReviewDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("entity_type", models.CharField(max_length=10)),
                ("entity_id", models.PositiveIntegerField()),
                ("issue", models.CharField(max_length=40)),
                ("fingerprint", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=24)),
                ("note", models.TextField(blank=True)),
                ("evidence_url", models.URLField(blank=True, max_length=1000)),
                ("deferred_until", models.DateField(blank=True, null=True)),
                ("snapshot", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlanCarryover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_month", models.DateField()),
                ("target_month", models.DateField()),
                (
                    "pages",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("reading_basis", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SavedDiscoveryFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("filters", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.AddField(
            model_name="planitem",
            name="carried_pages",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="planitem",
            name="pages_read",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="home_page",
            field=models.CharField(
                choices=[("explore", "Explore"), ("today", "Today")],
                default="explore",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="planitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("carried_pages", 0),
                    models.Q(
                        ("pages__gte", models.F("carried_pages")),
                        ("pages__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="plan_carry_within_pages",
            ),
        ),
        migrations.AddConstraint(
            model_name="planitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pages_read__isnull", True),
                    models.Q(
                        ("pages__isnull", False),
                        (
                            "pages_read__lte",
                            django.db.models.expressions.CombinedExpression(
                                models.F("pages"), "-", models.F("carried_pages")
                            ),
                        ),
                    ),
                    _connector="OR",
                ),
                name="plan_read_within_pages",
            ),
        ),
        migrations.AddField(
            model_name="catalogreviewdecision",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="plancarryover",
            name="source_plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carryovers_out",
                to="core.planitem",
            ),
        ),
        migrations.AddField(
            model_name="plancarryover",
            name="target_plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carryovers_in",
                to="core.planitem",
            ),
        ),
        migrations.AddField(
            model_name="plancarryover",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="plancarryover",
            name="work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.work"
            ),
        ),
        migrations.AddField(
            model_name="saveddiscoveryfilter",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_discovery_filters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="catalogreviewdecision",
            index=models.Index(
                fields=["entity_type", "entity_id", "issue", "created_at"],
                name="catalog_review_entity_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="saveddiscoveryfilter",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_user_discovery_filter"
            ),
        ),
    ]
