# Generated by Django 5.2.17 on 2026-09-28 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# Frozen data migration: never import a changing application storage adapter.
def split_records(state):
    from copy import deepcopy
    from hashlib import sha256
    import json
    small = deepcopy(state)
    paths = [('modules',), ('companion', 'commonplaces'), ('learning', 'essays'),
             ('learning', 'recall'), ('reading_desk', 'note'), ('reading_desk', 'exercise')]
    if isinstance(small.get('activities'), dict):
        paths.extend(('activities', version) for version in small['activities'])
    records = []
    for path in paths:
        target = small
        for part in path:
            target = target.get(part, {}) if isinstance(target, dict) else {}
        if not isinstance(target, dict):
            continue
        for key, value in list(target.items()):
            full_path = [*path, key]
            digest = sha256(json.dumps(full_path, ensure_ascii=False, separators=(',', ':')).encode()).hexdigest()
            records.append((digest, full_path, value))
            del target[key]
    return small, records


def forward(apps, schema_editor):
    Profile = apps.get_model('core', 'ClassicalStudyProfile')
    Record = apps.get_model('core', 'StudyRecord')
    database = schema_editor.connection.alias
    for profile in Profile.objects.using(database).iterator():
        small, records = split_records(profile.state)
        Record.objects.using(database).bulk_create([
            Record(user_id=profile.user_id, record_key=key, path=path, value=value)
            for key, path, value in records], batch_size=100)
        if records:
            Profile.objects.using(database).filter(pk=profile.pk).update(state=small)


def backward(apps, schema_editor):
    from copy import deepcopy
    Profile = apps.get_model('core', 'ClassicalStudyProfile')
    Record = apps.get_model('core', 'StudyRecord')
    database = schema_editor.connection.alias
    for profile in Profile.objects.using(database).iterator():
        state = deepcopy(profile.state)
        for row in Record.objects.using(database).filter(user_id=profile.user_id).iterator():
            target = state
            for part in row.path[:-1]:
                target = target.setdefault(part, {})
            target[row.path[-1]] = row.value
        Profile.objects.using(database).filter(pk=profile.pk).update(state=state)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_catalogreviewdecision_plancarryover_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("record_key", models.CharField(max_length=64)),
                ("path", models.JSONField()),
                ("value", models.JSONField(blank=True, default=dict, null=True)),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "record_key"),
                        name="unique_private_study_record",
                    )
                ],
            },
        ),
        migrations.RunPython(forward, backward),
    ]
