# Generated by Django 5.2.17 on 2026-09-28 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_studyrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="MutationReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=128)),
                ("request_hash", models.CharField(max_length=64)),
                ("status_code", models.PositiveSmallIntegerField()),
                ("response", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="mutation_receipt_created_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "key"), name="unique_private_mutation_key"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RecommendationFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("preferences", "preferences"),
                            ("neutral", "neutral"),
                            ("more_like", "more_like"),
                            ("not_interested", "not_interested"),
                            ("later", "later"),
                        ],
                        max_length=24,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("deferred_until", models.DateField(blank=True, null=True)),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "saved_filter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.saveddiscoveryfilter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.work",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "action"], name="recommendation_user_action"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "work"),
                        name="unique_recommendation_work_feedback",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("work__isnull", True)),
                        fields=("user",),
                        name="unique_recommendation_preferences",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("action", "preferences"), ("work__isnull", True)),
                            models.Q(
                                (
                                    "action__in",
                                    ["neutral", "more_like", "not_interested", "later"],
                                ),
                                ("saved_filter__isnull", True),
                                ("work__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="recommendation_feedback_target",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("action", "later"), ("deferred_until__isnull", False)
                            ),
                            models.Q(
                                models.Q(("action", "later"), _negated=True),
                                ("deferred_until__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="recommendation_deferral_consistent",
                    ),
                ],
            },
        ),
    ]
